//created on: 16 abr. 2022
package Rules

import com.eia.model.Lector;
import com.eia.model.DiagnosticoPreliminar;
import com.eia.model.EstadoDelLectorDeTarjetas;
import com.eia.model.CondicionLector;
import com.eia.model.Molinete;
import com.eia.model.EstadoDelMolinete;
import com.eia.model.CondicionMolinete;


rule "R1 - Lector no funcionando"
    when
    	$lector:Lector(condicion == CondicionLector.NO_FUNCIONANDO);
    then
        $lector.diagnosticoFinal.diagnosticoPreliminar
        .setEstadoDelLectorDeTarjetas(EstadoDelLectorDeTarjetas.DESHABILITADO);
    	update($lector);
end

rule "R2 - Lector funcionando"
    when
        $lector:Lector(condicion == CondicionLector.FUNCIONANDO);
    then
        $lector.diagnosticoFinal.diagnosticoPreliminar
        .setEstadoDelLectorDeTarjetas(EstadoDelLectorDeTarjetas.HABILITADO);
        update($lector);
end

rule "R3 - Molinete no funcionando"
    when
        $lector:Lector(molinete.condicion == CondicionMolinete.NO_FUNCIONANDO);
    then
        $lector.diagnosticoFinal.diagnosticoPreliminar.setEstadoDelMolinete(EstadoDelMolinete.DESHABILITADO);
end