package com.eia.model;

public enum Diagnostico {
	NO_DETERMINADO,
	SALDO_INSUFICIENTE,
	SUBE_NO_IDENTIFICADA,
	SUBE_DESHABILITADA,
	ERROR_DE_LECTURA,
	MOLINETE_DESHABILITADO,
	LECTOR_DESHABILITADO
}
